version: "2.1"
services:

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file:
      - ../.env
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/London
      - PASSWORD=${VSCODE_PASSWORD}
    volumes:
      - ./docker-data/csv/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

  nginx-proxy-man:
    image: jc21/nginx-proxy-manager:2
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./nginx-proxy-manager/config.json:/app/config/production.json
      - ./docker-data/nginx-man/data:/data
      - ./certs:/etc/letsencrypt
    depends_on:
      - db

  db:
    build: ./mariadb-aria/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'newp455w0rd'
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
